<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PEK5UDU" ignored="0" name="Test" tests="2" failures="1" timestamp="2021-12-21T10:07:57 IST" time="16.292" errors="0">
  <testcase name="signInNegative" time="4.721" classname="com.qa.tests.BholaPhonesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.tests.BholaPhonesTest.signInNegative(BholaPhonesTest.java:41)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- signInNegative -->
  <testcase name="signInPositive" time="4.154" classname="com.qa.tests.BholaPhonesTest"/>
</testsuite> <!-- Test -->
